### ISSUE TITLE
Basic Shell

### ISSUE THREAD

**Issue by Kryptos-FR** [Kryptos-FR/Avalonia.GameStudio#1]
**Description**
Create the main window of the application, with the minimum set of functionalities:
- dock controls with main area
- default menus

**Tasks**
- [x] main window
  - [x] dock regions
- [x] main menus
  - [x] file menu
  - [x] edit menu
  - [x] help menu

**Comment by ghost** [comment]
Happy to help, if your still up for this. Something like this needs a few of us :-) as it is massive.

**Comment by Kryptos-FR** [comment]
@communityus Thanks.

I haven't finalized my plans yet, as I did not have much time to spend on it.
I will try to have a bit more thought about it and then see how we can organize the work.

In the meantime, you can start familiarizing yourself with [Avalonia](https://github.com/AvaloniaUI/Avalonia), [ReactiveUI](https://github.com/dotnet/reactive) and the [Dock library](https://github.com/wieslawsoltes/Dock). The first few iterations will be around building a good base for the editor, that is agnostic of Xenko.

**Comment by ghost** [comment]
Thx. for the links. I will have a look.

Will part of the plan be to use the Avalonia approach to handling WinForms/WPF Xenko deps? I know that was a concern. My understanding of AvaloniaUI is that it is the spiritual successor to mono's first winforms approach and possibly even another grab at what the mono olive codebase was after. At least this is my understanding.

Part of my motivation for helping, aside from having Xenko on native Linux is to learn more about porting winforms to something universal, and somewhat user controlled.

I am playing around with winforms options on Linux presently. So I hopefully come in somewhat on same page. I am jr level developer - still learning :-) a lot.

**Comment by Kryptos-FR** [comment]
Avalonia is indeed a choice to replace the current code that is WPF (since WPF will most likely never be ported to other platforms).

That said, I don't intend to just port the current Xenko GameStudio to Avalonia, but to do a full rewrite, hopefully learning from the design mistake that were done there. One of the goal is to have a proper extensibility through plugins, but we can discuss that later.

I will be busy this weekend, so I'm not sure I will have time to look at and clarify my plan. Feel free to ping me in a week or two, in case I did not give any update.

To be honest, having someone else looking at it might finally give me the motivation to spend some time. But I don't want to get too many people involved before I finalize my vision of the new GameStudio.

Cheers

**Comment by ghost** [comment]
I have similar motivations. I will put this on my radar and ping you if needed in a few weeks :-)
